
＝＝＝＝＝＝＝＝＝＝
【日志级别】：ERROR
【记录时间】：2020-03-12 16:09:26,818 
【执行时间】：[131019]毫秒
捕捉到全局错误:System.Exception: 中间件异常测试
   at AspCoreTry.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in e:\AnnualTarget\NewFramework\MicroService\Core\AspCore\Try\AspCoreTry\Startup.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at Log4netMiddleware.Invoke(HttpContext context) in e:\AnnualTarget\NewFramework\MicroService\Core\AspCore\Try\AspCoreTry\Extend\Log\Log4netMiddleware.cs:line 22

＝＝＝＝＝＝＝＝＝＝
【日志级别】：ERROR
【记录时间】：2020-03-12 16:09:29,922 
【执行时间】：[134123]毫秒
捕捉到全局错误:System.Exception: 中间件异常测试
   at AspCoreTry.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in e:\AnnualTarget\NewFramework\MicroService\Core\AspCore\Try\AspCoreTry\Startup.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at Log4netMiddleware.Invoke(HttpContext context) in e:\AnnualTarget\NewFramework\MicroService\Core\AspCore\Try\AspCoreTry\Extend\Log\Log4netMiddleware.cs:line 22

＝＝＝＝＝＝＝＝＝＝
【日志级别】：DEBUG
【记录时间】：2020-03-12 16:13:04,395 
【执行时间】：[1070]毫秒
这是一个debug:03/12/2020 16:13:04

＝＝＝＝＝＝＝＝＝＝
【日志级别】：ERROR
【记录时间】：2020-03-12 16:13:25,372 
【执行时间】：[22047]毫秒
捕捉到全局错误:System.Exception: 这是一个测试异常
   at AspCoreTry.Controllers.HomeController.Privacy() in e:\AnnualTarget\NewFramework\MicroService\Core\AspCore\Try\AspCoreTry\Controllers\HomeController.cs:line 27
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at AspCoreTry.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in e:\AnnualTarget\NewFramework\MicroService\Core\AspCore\Try\AspCoreTry\Startup.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at Log4netMiddleware.Invoke(HttpContext context) in e:\AnnualTarget\NewFramework\MicroService\Core\AspCore\Try\AspCoreTry\Extend\Log\Log4netMiddleware.cs:line 22
